### ISSUE TITLE
Git urls

### ISSUE THREAD

**Issue by megawac** [stefanbuck/github-linker#22]
Git urls are a bit complicated and can come in the form of

```js
<user|org>/<repo> #link to githbb
<clone method>://<url>
```

It'd be sweet if support for these were added, I played with it myself but didn't get far

**Comment by stefanbuck** [comment]
@megawac implemented with version 3.4.0 https://github.com/stefanbuck/github-linker/blob/master/CHANGELOG.md#v340-2015-01-07
